### ISSUE TITLE
GET for nextJob

### ISSUE THREAD

**Issue by mcollina** [nicola/crowd#1]
I don't think it's a good idea.
You are really violating REST, a get should not alter any state.

**Comment by nicola** [comment]
do you mean this?
`GET /api/task/:taskId/next`

I think it should be a post instead

**Comment by mcollina** [comment]
These kind of stuff is usually modelled with a `DELETE`, because a task is just a queue.

**Comment by mcollina** [comment]
maybe you should even use queue terminology: `DELETE /api/task/:taskId/queue/head`

**Comment by nicola** [comment]
I am not sure about this.
I personally don't agree.
This call will be called only if someone wants to skip a job, since the ideal workflow is

`get TASK`
`post Solution` <- this will contain the next task
(machine will execute)
`post Solution` (again and again)

In case I want to go to next task I can do `GET /api/task:taskId/next` which is exactly the next in queue, no state is altered I believe.

**Comment by mcollina** [comment]
I see, the problem is in the workflow :).

You do not have to `GET` a task, that's the whole point.
You are in a distributed system, so clients will concurrent ask for a task to run.
A `GET` should not alter the internal state.

**Comment by nicola** [comment]
new design from commit 4739a0635ed57ac8b8f64721f8e0c00b6efee233
